FROM node:20-alpine

ARG PORT_ARG=3000
ARG HOST_ARG=0.0.0.0
ARG SENTRY_HOST_ARG
ARG SENTRY_PROJECT_IDS_ARG

WORKDIR /usr/sentry-tunnel-handler
COPY ["./package.json", "./package-lock.json", "./"]
RUN npm install
COPY ./ ./

ENV HOST=$HOST_ARG
ENV PORT=$PORT_ARG
ENV SENTRY_HOST=$SENTRY_HOST
ENV SENTRY_PROJECT_IDS=$SENTRY_PROJECT_IDS

EXPOSE $PORT
CMD ["npm", "start"]
